### ISSUE TITLE
compiling projects on windows gives weird error.

### ISSUE THREAD

**Issue by shah-ee** [hmrc/sbt-auto-build#44]
# Issue

Building a project that uses the plugin in windows gives the following error:

> java.lang.RuntimeException: SbtAutoBuildPlugin - Error, please fix: The LICENSE file does not contain the appropriate Apache V2 licence. It should match https://www.apache.org/licenses/LICENSE-2.0.txt
        at scala.sys.package$.error(package.scala:30)
        at uk.gov.hmrc.HeaderUtils$.shouldGenerateHeaders(HeaderUtils.scala:83)
        at uk.gov.hmrc.HeaderSettings$.$anonfun$apply$8(SbtAutoBuildPlugin.scala:134)
        at uk.gov.hmrc.HeaderSettings$.$anonfun$apply$8$adapted(SbtAutoBuildPlugin.scala:133)
        at scala.Function1.$anonfun$compose$1(Function1.scala:49)
        at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:228)
        at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:170)
        at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
        at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
        at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[error] SbtAutoBuildPlugin - Error, please fix: The LICENSE file does not contain the appropriate Apache V2 licence. It should match https://www.apache.org/licenses/LICENSE-2.0.txt

# Steps to reproduce

- have openJdk java installed (tested it with both v8, v16)
- take a library that uses `sbt-auto-build`, say a nice and simple one such as https://github.com/hmrc/platform-progress-metrics
- clone it in windows and run `sbt build` on the project.

  note that the project does in fact have the license, ie: https://github.com/hmrc/platform-progress-metrics/blob/main/LICENSE as it was auto-geenrated by Jenkins.

**Comment by shah-ee** [comment]
can confirm the tests fail on windows:

- > should return an error if the file does not exist *** FAILED ***
[info]   Left("Unable to find repository.yaml file at D:\Users\shahab\IdeaProjects\hmrc\sbt-auto-build\missing\repository.yaml. See https://confluence.tools.tax.service.gov.uk/x/k_8TCQ") was not equal to Left("Unable to find repository.yaml file at D:\Users\shahab\IdeaProjects\hmrc\sbt-auto-build\missing/repository.yaml. See https://confluence.tools.tax.service.gov.uk/x/k_8TCQ") (RepositoryYamlUtilsSpec.scala:30)
- > should return the correct MD5 hash of the licence file (older variant with {} instead of []) *** FAILED ***
[info]   "[3d113347136ff8800e34bb85c10182e0]" was not equal to "[6c4db32a2fa8717faffa1d4f10136f47]" (HeaderUtilsSpec.scala:32)
 - > should return the correct MD5 hash of the licence file (current) *** FAILED ***
[info]   "[733ee64399ecdc51b3ab17c423271ccb]" was not equal to "[cc1a9e33dd7a6eb0b79927742cf005c]" (HeaderUtilsSpec.scala:38)

**Comment by ubiuser** [comment]
I also ran into this license issue, but when I compared the original Apache V2 licence with the one referenced in https://github.com/hmrc/service-dependencies/blob/HEAD/LICENSE, I found that there are indeed differences. The HMRC version on line https://github.com/hmrc/service-dependencies/blob/HEAD/LICENSE#L181 and https://github.com/hmrc/service-dependencies/blob/HEAD/LICENSE#L189 uses `{}`, whereas Apache uses `[]`. The Apache license file also starts with an empty line.

Once I copied the HMRC version into the project I was looking into (https://github.com/[hmrc/self-employment-business-api](https://github.com/hmrc/self-employment-business-api)), the issue got resolved and I was able to run sbt.
